#! /bin/bash

sudo podman pod create --name caddypod \
	-p 80:80 \
	-p 443:443 \
	-p 443:443/udp 

# Caddy
sudo podman run -d --pod caddypod \
	--name caddy \
	-v $PWD/config:/etc/caddy \
	-v /etc/localtime:/etc/localtime:ro \
	--restart unless-stopped \
docker.io/caddy:latest

# Caddy with cloudflare
sudo podman run -d --pod caddypod \
 --name caddy-cloudflared \
 -v $PWD/config:/etc/caddy \
 -v /etc/localtime:/etc/localtime:ro \
 --restart unless-stopped \
 docker.io/caddy-cloudflare:latest
