#! /bin/bash

podman pod create --name caddypod -p 80:80 -p 443:443 \

podman run -d --pod caddypod \
 --name caddy \
 -v $PWD/Caddyfile:/etc/caddy/Caddyfile \
 -v $PWD/site:/srv \
 -v caddy_data:/data \
 -v caddy_config:/config \
 caddy:2.5.1-alpine


