#! /bin/bash
# Create a bookstack instance for ARM64

# Create the books pod
podman pod create --name books --infra-name booksinf \
 -p 6875:80

mkdir data 

# Bookstack container
# APP_URL has to be the complete URL e.g
# https://192.168.0.200:8080
# http://example.com:port
# Provide a mariadb for this pod
podman run -d --pod books \
 -e PUID=1000 \
 -e PGID=1000 \
 -e APP_URL="" \
 -e DB_HOST=book_host \
 -e DB_USER=book_user \
 -e DB_PASS="changeme" \
 -e DB_DATABASE=book_db \
 -v $PWD/data:/config \
 --restart unless-stopped \
 --name bookstack \
lscr.io/linuxserver/bookstack:arm64v8-22.04.2 

